version: 2.1

jobs:
  create_infrastructure:

    docker:
      - image: amazon/aws-cli

    steps:
      - checkout
      - run:
          name: "create-infrastructure"
          command: |
              aws cloudformation deploy \
                --template-file template.yml \
                --stack-name FwdServer \
                --region us-east-1

  configure_infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
      
              fingerprints: ["ad:c6:9a:bb:39:df:84:ef:3e:65:cc:40:5d:d8:68:8a"] 
      - run:
          name: Install Ansible
          command: |
            apk add --update ansible
      - run:
          name: Run Playbook and Configure server
          command: |
            ansible-playbook -i inventory.txt main.yml

workflows:
  create_infrastructure-workflow:
    jobs:
      - create_infrastructure
      #- configure_infrastructure

